os: linux
dist: bionic
language: node_js
node_js:
  - '10'
jobs:
  include:
    - stage: Build
      name: Build
      script: npm run build
    - name: Lint
      script: npm run lint
    - name: Security
      script: npm audit && npm audit --prefix functions
    - stage: Test
      name: Unit
      script: npm test
  allow_failures:
    - name: Security
